### ISSUE TITLE
Pretrained model?

### ISSUE THREAD

**Issue by yashkumaratri** [jonnykira/openai_reproduction#1]
Can we get the pre trained model the one's trained by you on amazon data set?

**Comment by jonny-d** [comment]
Hello! Apologies for the late response.

I have added the pre-trained weights in the `model` folder.  To use the pre-trained weights, run the following line:

`cat ./model/994/x* > ./model/994/model.npy`

This will concatenate 4 files to produce `model.npy`. The `model.npy` was above the file size limit for Github so I had to split it before uploading. You can then run `sst_binary_demo.py` to classify the Stanford Sentiment data with the pre-trained model and visualize the sentiment neuron unit. I have also added a bit to the readme explaining this. 

Hope this helps!

**Comment by yashkumaratri** [comment]
What's the issue now ?

test.py
```
from encoder import Model
from utils import sst_binary, train_with_reg_cv
import numpy as np
import os
import pandas as pd
import time

model = Model('./model/994/model.npy')
text = "Show an example of a longer sentence,  "
out_text = text
text_features= model.transform(out_text)
sent = text_features[:,3984]

print(sentiment)
```


```
(python3) ion@aurora:~/Pictures/openai_reproduction$ python test.py 
Traceback (most recent call last):
  File "/home/ion/python3/lib/python3.5/site-packages/numpy/lib/format.py", line 650, in read_array
    array = pickle.load(fp, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9f in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    model = Model('./model/994/model.npy')
  File "/home/ion/Pictures/openai_reproduction/encoder.py", line 137, in __init__
    params = concatenate_for_encoder(restore_path)
  File "/home/ion/Pictures/openai_reproduction/utils.py", line 105, in concatenate_for_encoder
    weights_list = np.load(checkpoint_path)
  File "/home/ion/python3/lib/python3.5/site-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/ion/python3/lib/python3.5/site-packages/numpy/lib/format.py", line 656, in read_array
    "to numpy.load" % (err,))
UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'\x9fvZ=\xd6\xae>\xbd\xdd\xa3\xf0;\xd0\xb1{=Z\\&\xbd\xee@k\xbd\x0e\x93\x0f\xbe\x84\xad\xbe\xbcYl\xd2=KzO<\tw\xeb=Y\x10\x10>\x85F\xcb=\xba$\x97=\xa7]\xc0=wl1=*I\x1d\xbdQ\x1a\x95=\xb4\x8b\xa0\xbdh\x19<=\x1c\x13o\xbaM\x08\x82\xbc\xd0\x07\xe1<\xd4e\xdc\xbb
```

**Comment by jonny-d** [comment]
It looks like there is an incompatibility issue with Pickle between python2 and python3. The openai_reproduction code was developed using python2 and it looks like you are using python3 here.

Looks like this should help:
https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3/28218598#28218598
